const result = [
    {
        id: '1',
        name: 'Đất',
        attributes: [
            { id: '1', name: 'area', displayName: 'Diện tích', displayOrder: 1, type: 'number', unit: 'm²', required: true },
            { id: '2', name: 'roadWidth', displayName: 'Đường trước nhà', displayOrder: 2, type: 'number', unit: 'm', required: false },
            {
                id: '3',
                name: 'legalDocument',
                displayName: 'Giấy tờ pháp lý',
                displayOrder: 3,
                type: 'select',
                required: false,
                attributes: [
                    { id: '1', name: 'red', displayName: 'Sổ đỏ', type: 'option', displayOrder: 1 },
                    { id: '2', name: 'pink', displayName: 'Sổ hồng', type: 'option', displayOrder: 2 },
                    { id: '3', name: 'buildLicense', displayName: 'Có giấy phép xây dựng', type: 'option', displayOrder: 3 },
                ],
            },
            {
                id: '4',
                name: 'direction',
                displayName: 'Hướng',
                displayOrder: 4,
                type: 'select',
                required: false,
                attributes: [
                    { id: '4', name: 'east', displayName: 'Đông', type: 'option', displayOrder: 1 },
                    { id: '5', name: 'west', displayName: 'Tây', type: 'option', displayOrder: 2 },
                    { id: '6', name: 'south', displayName: 'Nam', type: 'option', displayOrder: 3 },
                    { id: '7', name: 'north', displayName: 'Bắc', type: 'option', displayOrder: 4 },
                    { id: '8', name: 'northEast', displayName: 'Đông Bắc', type: 'option', displayOrder: 5 },
                    { id: '9', name: 'northWest', displayName: 'Tây Bắc', type: 'option', displayOrder: 6 },
                    { id: '10', name: 'southEast', displayName: 'Đông Nam', type: 'option', displayOrder: 7 },
                    { id: '11', name: 'southWest', displayName: 'Tây Name', type: 'option', displayOrder: 8 },
                    { id: '12', name: 'Unknown', displayName: 'Không xác địng', type: 'option', displayOrder: 9 },
                ],
            },
            { id: '5', name: 'numberOfBedroom', displayName: 'Số phòng ngủ', displayOrder: 5, type: 'number', required: false },
            { id: '6', name: 'numberOfLivingroom', displayName: 'Số phòng khách', displayOrder: 6, type: 'number', required: false },
            { id: '7', name: 'numberOfBathroom', displayName: 'Số phòng tắm', displayOrder: 7, type: 'number', required: false },
            { id: '8', name: 'numberOfFloor', displayName: 'Số tầng', displayOrder: 8, type: 'number', required: false },
            {
                id: '9',
                name: 'utility',
                displayName: 'Tiện nghi',
                displayOrder: 9,
                type: 'group',
                required: false,
                attributes: [
                    { id: '13', name: 'swimmingpool', displayName: 'Hồ bơi', type: 'checkbox', displayOrder: 1 },
                    { id: '14', name: 'washingmachine', displayName: 'Máy giặt', type: 'checkbox', displayOrder: 2 },
                    { id: '15', name: 'wifi', displayName: 'Wifi', type: 'checkbox', displayOrder: 3 },
                    { id: '16', name: 'garden', displayName: 'Sân vườn', type: 'checkbox', displayOrder: 4 },
                    { id: '17', name: 'fullfurniture', displayName: 'Đầy đủ nội thất', type: 'checkbox', displayOrder: 5 },
                    { id: '18', name: 'airconditioner', displayName: 'Điều hòa', type: 'checkbox', displayOrder: 6 },
                    { id: '19', name: 'balcony', displayName: 'Ban công', type: 'checkbox', displayOrder: 7 },
                    { id: '20', name: 'gym', displayName: 'Phòng tập Gym', type: 'checkbox', displayOrder: 8 },
                    { id: '21', name: 'opticalfiberinternet', displayName: 'Internet cáp quang', type: 'checkbox', displayOrder: 9 },
                ],
            },
            {
                id: '10',
                name: 'environment',
                displayName: 'Môi trường xung quanh',
                displayOrder: 10,
                type: 'group',
                required: false,
                attributes: [
                    { id: '22', name: 'supermarket', displayName: 'Siêu thị', type: 'checkbox', displayOrder: 1 },
                    { id: '23', name: 'school', displayName: 'Trường học', type: 'checkbox', displayOrder: 2 },
                    { id: '24', name: 'beach', displayName: 'Gần biển', type: 'checkbox', displayOrder: 3 },
                    { id: '25', name: 'hospital', displayName: 'Bệnh viện', type: 'checkbox', displayOrder: 4 },
                    { id: '26', name: 'park', displayName: 'Công viên', type: 'checkbox', displayOrder: 5 },
                    { id: '27', name: 'temple', displayName: 'Gần chùa', type: 'checkbox', displayOrder: 6 },
                    { id: '28', name: 'publictraffic', displayName: 'Giao thông công cộng', type: 'checkbox', displayOrder: 7 },
                    { id: '29', name: 'safetyarea', displayName: 'Khu vực an ninh', type: 'checkbox', displayOrder: 8 },
                    { id: '30', name: 'church', displayName: 'Gần nhà thờ', type: 'checkbox', displayOrder: 9 },
                ],
            },
        ],
    },
    {
        id: '2',
        name: 'Nhà',
        attributes: [
            { id: '1', name: 'area', displayName: 'Diện tích', displayOrder: 1, type: 'number', unit: 'm²', required: true },
            { id: '2', name: 'roadWidth', displayName: 'Đường trước nhà', displayOrder: 2, type: 'number', unit: 'm', required: false },
            {
                id: '3',
                name: 'legalDocument',
                displayName: 'Giấy tờ pháp lý',
                displayOrder: 3,
                type: 'select',
                required: false,
                attributes: [
                    { id: '1', name: 'red', displayName: 'Sổ đỏ', type: 'option', displayOrder: 1 },
                    { id: '2', name: 'pink', displayName: 'Sổ hồng', type: 'option', displayOrder: 2 },
                    { id: '3', name: 'buildLicense', displayName: 'Có giấy phép xây dựng', type: 'option', displayOrder: 3 },
                ],
            },
            {
                id: '4',
                name: 'direction',
                displayName: 'Hướng',
                displayOrder: 4,
                type: 'select',
                required: false,
                attributes: [
                    { id: '4', name: 'east', displayName: 'Đông', type: 'option', displayOrder: 1 },
                    { id: '5', name: 'west', displayName: 'Tây', type: 'option', displayOrder: 2 },
                    { id: '6', name: 'south', displayName: 'Nam', type: 'option', displayOrder: 3 },
                    { id: '7', name: 'north', displayName: 'Bắc', type: 'option', displayOrder: 4 },
                    { id: '8', name: 'northEast', displayName: 'Đông Bắc', type: 'option', displayOrder: 5 },
                    { id: '9', name: 'northWest', displayName: 'Tây Bắc', type: 'option', displayOrder: 6 },
                    { id: '10', name: 'southEast', displayName: 'Đông Nam', type: 'option', displayOrder: 7 },
                    { id: '11', name: 'southWest', displayName: 'Tây Name', type: 'option', displayOrder: 8 },
                    { id: '12', name: 'Unknown', displayName: 'Không xác địng', type: 'option', displayOrder: 9 },
                ],
            },
            { id: '5', name: 'numberOfBedroom', displayName: 'Số phòng ngủ', displayOrder: 5, type: 'number', required: false },
            { id: '6', name: 'numberOfLivingroom', displayName: 'Số phòng khách', displayOrder: 6, type: 'number', required: false },
            { id: '7', name: 'numberOfBathroom', displayName: 'Số phòng tắm', displayOrder: 7, type: 'number', required: false },
            { id: '8', name: 'numberOfFloor', displayName: 'Số tầng', displayOrder: 8, type: 'number', required: false },
            {
                id: '9',
                name: 'utility',
                displayName: 'Tiện nghi',
                displayOrder: 9,
                type: 'group',
                required: false,
                attributes: [
                    { id: '13', name: 'swimmingpool', displayName: 'Hồ bơi', type: 'checkbox', displayOrder: 1 },
                    { id: '14', name: 'washingmachine', displayName: 'Máy giặt', type: 'checkbox', displayOrder: 2 },
                    { id: '15', name: 'wifi', displayName: 'Wifi', type: 'checkbox', displayOrder: 3 },
                    { id: '16', name: 'garden', displayName: 'Sân vườn', type: 'checkbox', displayOrder: 4 },
                    { id: '17', name: 'fullfurniture', displayName: 'Đầy đủ nội thất', type: 'checkbox', displayOrder: 5 },
                    { id: '18', name: 'airconditioner', displayName: 'Điều hòa', type: 'checkbox', displayOrder: 6 },
                    { id: '19', name: 'balcony', displayName: 'Ban công', type: 'checkbox', displayOrder: 7 },
                    { id: '20', name: 'gym', displayName: 'Phòng tập Gym', type: 'checkbox', displayOrder: 8 },
                    { id: '21', name: 'opticalfiberinternet', displayName: 'Internet cáp quang', type: 'checkbox', displayOrder: 9 },
                ],
            },
            {
                id: '10',
                name: 'environment',
                displayName: 'Môi trường xung quanh',
                displayOrder: 10,
                type: 'group',
                required: false,
                attributes: [
                    { id: '22', name: 'supermarket', displayName: 'Siêu thị', type: 'checkbox', displayOrder: 1 },
                    { id: '23', name: 'school', displayName: 'Trường học', type: 'checkbox', displayOrder: 2 },
                    { id: '24', name: 'beach', displayName: 'Gần biển', type: 'checkbox', displayOrder: 3 },
                    { id: '25', name: 'hospital', displayName: 'Bệnh viện', type: 'checkbox', displayOrder: 4 },
                    { id: '26', name: 'park', displayName: 'Công viên', type: 'checkbox', displayOrder: 5 },
                    { id: '27', name: 'temple', displayName: 'Gần chùa', type: 'checkbox', displayOrder: 6 },
                    { id: '28', name: 'publictraffic', displayName: 'Giao thông công cộng', type: 'checkbox', displayOrder: 7 },
                    { id: '29', name: 'safetyarea', displayName: 'Khu vực an ninh', type: 'checkbox', displayOrder: 8 },
                    { id: '30', name: 'church', displayName: 'Gần nhà thờ', type: 'checkbox', displayOrder: 9 },
                ],
            },
        ],
    },
    {
        id: '3',
        name: 'Căn hộ',
        attributes: [
            { id: '1', name: 'area', displayName: 'Diện tích', displayOrder: 1, type: 'number', unit: 'm²', required: true },
            { id: '2', name: 'roadWidth', displayName: 'Đường trước nhà', displayOrder: 2, type: 'number', unit: 'm', required: false },
            {
                id: '3',
                name: 'legalDocument',
                displayName: 'Giấy tờ pháp lý',
                displayOrder: 3,
                type: 'select',
                required: false,
                attributes: [
                    { id: '1', name: 'red', displayName: 'Sổ đỏ', type: 'option', displayOrder: 1 },
                    { id: '2', name: 'pink', displayName: 'Sổ hồng', type: 'option', displayOrder: 2 },
                    { id: '3', name: 'buildLicense', displayName: 'Có giấy phép xây dựng', type: 'option', displayOrder: 3 },
                ],
            },
            {
                id: '4',
                name: 'direction',
                displayName: 'Hướng',
                displayOrder: 4,
                type: 'select',
                required: false,
                attributes: [
                    { id: '4', name: 'east', displayName: 'Đông', type: 'option', displayOrder: 1 },
                    { id: '5', name: 'west', displayName: 'Tây', type: 'option', displayOrder: 2 },
                    { id: '6', name: 'south', displayName: 'Nam', type: 'option', displayOrder: 3 },
                    { id: '7', name: 'north', displayName: 'Bắc', type: 'option', displayOrder: 4 },
                    { id: '8', name: 'northEast', displayName: 'Đông Bắc', type: 'option', displayOrder: 5 },
                    { id: '9', name: 'northWest', displayName: 'Tây Bắc', type: 'option', displayOrder: 6 },
                    { id: '10', name: 'southEast', displayName: 'Đông Nam', type: 'option', displayOrder: 7 },
                    { id: '11', name: 'southWest', displayName: 'Tây Name', type: 'option', displayOrder: 8 },
                    { id: '12', name: 'Unknown', displayName: 'Không xác địng', type: 'option', displayOrder: 9 },
                ],
            },
            { id: '5', name: 'numberOfBedroom', displayName: 'Số phòng ngủ', displayOrder: 5, type: 'number', required: false },
            { id: '6', name: 'numberOfLivingroom', displayName: 'Số phòng khách', displayOrder: 6, type: 'number', required: false },
            { id: '7', name: 'numberOfBathroom', displayName: 'Số phòng tắm', displayOrder: 7, type: 'number', required: false },
            { id: '8', name: 'numberOfFloor', displayName: 'Số tầng', displayOrder: 8, type: 'number', required: false },
            {
                id: '9',
                name: 'utility',
                displayName: 'Tiện nghi',
                displayOrder: 9,
                type: 'group',
                required: false,
                attributes: [
                    { id: '13', name: 'swimmingpool', displayName: 'Hồ bơi', type: 'checkbox', displayOrder: 1 },
                    { id: '14', name: 'washingmachine', displayName: 'Máy giặt', type: 'checkbox', displayOrder: 2 },
                    { id: '15', name: 'wifi', displayName: 'Wifi', type: 'checkbox', displayOrder: 3 },
                    { id: '16', name: 'garden', displayName: 'Sân vườn', type: 'checkbox', displayOrder: 4 },
                    { id: '17', name: 'fullfurniture', displayName: 'Đầy đủ nội thất', type: 'checkbox', displayOrder: 5 },
                    { id: '18', name: 'airconditioner', displayName: 'Điều hòa', type: 'checkbox', displayOrder: 6 },
                    { id: '19', name: 'balcony', displayName: 'Ban công', type: 'checkbox', displayOrder: 7 },
                    { id: '20', name: 'gym', displayName: 'Phòng tập Gym', type: 'checkbox', displayOrder: 8 },
                    { id: '21', name: 'opticalfiberinternet', displayName: 'Internet cáp quang', type: 'checkbox', displayOrder: 9 },
                ],
            },
            {
                id: '10',
                name: 'environment',
                displayName: 'Môi trường xung quanh',
                displayOrder: 10,
                type: 'group',
                required: false,
                attributes: [
                    { id: '22', name: 'supermarket', displayName: 'Siêu thị', type: 'checkbox', displayOrder: 1 },
                    { id: '23', name: 'school', displayName: 'Trường học', type: 'checkbox', displayOrder: 2 },
                    { id: '24', name: 'beach', displayName: 'Gần biển', type: 'checkbox', displayOrder: 3 },
                    { id: '25', name: 'hospital', displayName: 'Bệnh viện', type: 'checkbox', displayOrder: 4 },
                    { id: '26', name: 'park', displayName: 'Công viên', type: 'checkbox', displayOrder: 5 },
                    { id: '27', name: 'temple', displayName: 'Gần chùa', type: 'checkbox', displayOrder: 6 },
                    { id: '28', name: 'publictraffic', displayName: 'Giao thông công cộng', type: 'checkbox', displayOrder: 7 },
                    { id: '29', name: 'safetyarea', displayName: 'Khu vực an ninh', type: 'checkbox', displayOrder: 8 },
                    { id: '30', name: 'church', displayName: 'Gần nhà thờ', type: 'checkbox', displayOrder: 9 },
                ],
            },
        ],
    },
];

export default result;
